#!/usr/bin/env python3
"""tools/gen_sheets.py — assets/parts/sheet_*.png → src/display/art/art_sheet_*.h

sheet_gear.png (1024x1024 2x2) と sheet_hud.png (1024x256 1x4) を
E-Ink用1bit XBMヘッダに変換する。jpg2ink.py to_bitmap と同一bit順
(LSB first, row-major, 黒=1) で出力する。

- gear: 24x24、bmp + silhouette mask (穴埋め。drawPartの白抜き+黒描画用)
- hud: 16x16、bmpのみ (モニタ域は白背景のため黒点のみ描画で足りる)

マスクは flood fill で外側背景と連結した白だけを背景とみなし、
連結していない白 (水滴ハイライト・笑顔の内側等) を穴として
シルエットに含める。背景透過を保ちつつ内側白抜きを再現できる。

使い方:
  python tools/gen_sheets.py          # 両シート変換
  python tools/gen_sheets.py --check  # 変換せずASCII確認のみ
"""
import argparse
import os
import sys
from collections import deque

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from jpg2ink import to_bitmap  # bit順の単一実装を使い回す

GEAR_SZ = 24
HUD_SZ = 16

# (sheet内セル, 変数名, 一辺)
GEAR_CELLS = [
    ((0, 0, 512, 512), "gear11_star", "ID11 ほし星"),
    ((512, 0, 1024, 512), "gear8_swirl", "ID8 うず渦"),
    ((0, 512, 512, 1024), "gear0_drop", "ID0 まる水滴"),
    ((512, 512, 1024, 1024), "gear4_stripe", "ID4 しま縞"),
]
HUD_CELLS = [
    ((0, 0, 256, 256), "hud_hp", "HP ハート"),
    ((256, 0, 512, 256), "hud_sat", "SAT 肉"),
    ((512, 0, 768, 256), "hud_en", "EN 雷"),
    ((768, 0, 1024, 256), "hud_ha", "HA 笑顔"),
]


def cell_to_mono(sheet, box, size):
    """セル→黒bboxタイト切り出し(+15%パッド・正方形化)→sizeへNEAREST縮小→1bit化。"""
    cell = sheet.crop(box).convert("L")
    inv = Image.eval(cell, lambda v: 255 - v)
    bb = inv.getbbox()
    assert bb, "空セル"
    x0, y0, x1, y1 = bb
    bw, bh = x1 - x0, y1 - y0
    pad = int(max(bw, bh) * 0.15) + 2
    # 正方形化 (長い辺に合わせ中央寄せ)
    side = max(bw, bh) + pad * 2
    cx, cy = x0 + bw / 2, y0 + bh / 2
    sx0, sy0 = int(cx - side / 2), int(cy - side / 2)
    # セル内へクランプ
    cw, ch = cell.size
    sx0 = max(0, min(cw - side, sx0))
    sy0 = max(0, min(ch - side, sy0))
    crop = cell.crop((sx0, sy0, sx0 + side, sy0 + side))
    return crop.resize((size, size), Image.NEAREST).point(lambda v: 0 if v < 128 else 255)


def silhouette(black):
    """black[y][x] (1=黒) → 外側背景と非連結の白を穴として埋めたsil[y][x] (1=塗り)。"""
    h = len(black)
    w = len(black[0])
    seen = [[False] * w for _ in range(h)]
    q = deque()
    for x in range(w):
        for y in (0, h - 1):
            if not black[y][x] and not seen[y][x]:
                seen[y][x] = True
                q.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            if not black[y][x] and not seen[y][x]:
                seen[y][x] = True
                q.append((x, y))
    while q:
        x, y = q.popleft()
        for nx, ny in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if 0 <= nx < w and 0 <= ny < h and not black[ny][nx] and not seen[ny][nx]:
                seen[ny][nx] = True
                q.append((nx, ny))
    # 背景到達=seen。穴=白かつ未到達 → シルエットに含める
    return [[1 if (black[y][x] or not seen[y][x]) else 0 for x in range(w)] for y in range(h)]


def to_xbm_bytes(mat):
    """0/1行列 → XBMバイト列 (LSB first, row-major, 1=黒/塗り)。"""
    h = len(mat)
    w = len(mat[0])
    out = bytearray()
    for y in range(h):
        byte = 0
        bits = 0
        for x in range(w):
            if mat[y][x]:
                byte |= 1 << bits
            bits += 1
            if bits == 8:
                out.append(byte)
                byte = 0
                bits = 0
        if bits:
            out.append(byte)
    return bytes(out)


def ascii_art(img1):
    px = img1.load()
    w, h = img1.size
    return "\n".join(
        "".join("##" if px[x, y] == 0 else "  " for x in range(w)) for y in range(h)
    )


def build(sheet_path, cells, size, with_mask):
    sheet = Image.open(sheet_path).convert("L")
    # 純2値検証 (グレー混入の早期検出)
    vals = set(sheet.getdata())
    assert vals <= {0, 255}, f"{sheet_path}: 中間色混入 {sorted(vals)[:8]}"
    icons = []
    for box, var, label in cells:
        mono = cell_to_mono(sheet, box, size)
        w, h = mono.size
        px = mono.load()
        black = [[1 if px[x, y] == 0 else 0 for x in range(w)] for y in range(h)]
        nb = sum(sum(r) for r in black)
        assert nb > 0, f"{label}: 空セル"
        bmp = to_xbm_bytes(black)
        # jpg2ink実装との一致確認 (二重実装の乖離防止)
        assert bmp == to_bitmap(mono), f"{label}: XBM実装乖離"
        mask = to_xbm_bytes(silhouette(black)) if with_mask else None
        icons.append((var, label, bmp, mask, ascii_art(mono), nb))
    return icons


def emit_header(path, src_label, size, icons, with_mask):
    with open(path, "w") as f:
        f.write("#pragma once\n")
        f.write(f"// auto-generated by tools/gen_sheets.py from {src_label}\n")
        f.write(f"// {size}x{size} XBM. 黒=描画。maskは内側白抜き(ハイライト等)再現用の\n")
        f.write("// シルエット (drawPartの白抜き→黒描画で背景透過を保つ)。\n\n")
        f.write("#include <Arduino.h>\n\n")
        for var, label, bmp, mask, _art, _nb in icons:
            wb = (size + 7) // 8
            assert len(bmp) == wb * size
            f.write(f"// {label}\n")
            f.write(f"#define {var.upper()}_W {size}\n#define {var.upper()}_H {size}\n\n")
            f.write(f"static const unsigned char {var}_bmp[{len(bmp)}] PROGMEM = {{\n")
            for i in range(0, len(bmp), 12):
                f.write("  " + ", ".join(f"0x{b:02x}" for b in bmp[i:i + 12]) + ",\n")
            f.write("};\n")
            if with_mask:
                assert mask is not None and len(mask) == len(bmp)
                f.write(f"static const unsigned char {var}_mask[{len(mask)}] PROGMEM = {{\n")
                for i in range(0, len(mask), 12):
                    f.write("  " + ", ".join(f"0x{b:02x}" for b in mask[i:i + 12]) + ",\n")
                f.write("};\n")
            f.write("\n")
    # 目視用プレビュー (3倍NEAREST)
    sheet = None
    print(f"wrote {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    gear_path = os.path.join(ROOT, "assets", "parts", "sheet_gear.png")
    hud_path = os.path.join(ROOT, "assets", "parts", "sheet_hud.png")
    gear = build(gear_path, GEAR_CELLS, GEAR_SZ, True)
    hud = build(hud_path, HUD_CELLS, HUD_SZ, False)
    for var, label, bmp, mask, art, nb in gear + hud:
        print(f"--- {label} ({var}) black={nb} bmp={len(bmp)}B"
              + (f" mask={len(mask)}B" if mask else ""))
        print(art)
    if a.check:
        return
    disp = os.path.join(ROOT, "src", "display", "art")
    emit_header(os.path.join(disp, "art_sheet_gear.h"), "assets/parts/sheet_gear.png",
                GEAR_SZ, gear, True)
    emit_header(os.path.join(disp, "art_sheet_hud.h"), "assets/parts/sheet_hud.png",
                HUD_SZ, hud, False)


if __name__ == "__main__":
    main()
