#!/usr/bin/env python3
"""tools/gen_morphs.py — 凍結中 (FROZEN)。12形態idleの手続き生成器だったが、
現行マスタ (JPG写真・手作り絵) と競合するため既定で書き込まない。
実行には --force が必須。--force なしでは何も書かずに終了する。
将来の形態追加時に再評価すること。
"""
import math
import os
import random
import sys

from PIL import Image, ImageDraw

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from jpg2ink import to_bitmap, ascii_preview

S = 96
BLACK = 0
WHITE = 255

# ---- screen.h gear ????? ----
SPOTS = [(8, 70, 6, 6), (82, 70, 6, 6), (14, 82, 4, 4), (78, 82, 4, 4)]
TG = [(30, 18, 27, 10), (48, 14, 48, 6), (66, 18, 69, 10), (14, 40, 7, 37),
      (14, 60, 7, 63), (82, 40, 89, 37), (82, 60, 89, 63), (30, 80, 27, 88),
      (66, 80, 69, 88), (48, 82, 48, 90)]
STRIPES = [(6, 66, 84, 4), (10, 74, 76, 3), (16, 82, 64, 4)]
WHISK = [(24, 54, 8, 50), (24, 60, 8, 60), (24, 66, 8, 70),
         (72, 54, 88, 50), (72, 60, 88, 60), (72, 66, 88, 70)]
STARS = [(14, 14), (82, 14), (14, 82), (82, 82)]


def circle(d, cx, cy, r, fill=None, outline=None, width=1):
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=fill, outline=outline, width=width)


def rect(d, x, y, w, h):
    d.rectangle([x, y, x + w - 1, y + h - 1], fill=BLACK)


def paint_base(d):
    for x0, x1 in ((28, 40), (56, 70)):
        d.ellipse([x0, 78, x1, 94], fill=WHITE, outline=BLACK, width=2)
    d.ellipse([18, 24, 78, 88], fill=WHITE)
    d.ellipse([18, 24, 78, 88], outline=BLACK, width=2)


def paint_face(d, seed):
    rng = random.Random(seed)
    placed, guard = 0, 0
    while placed < 14 and guard < 600:
        guard += 1
        x, y = rng.randint(20, 76), rng.randint(28, 84)
        if ((x - 48) / 28) ** 2 + ((y - 56) / 30) ** 2 > 0.80:
            continue
        if math.hypot(x - 44, y - 42) < 16:
            continue
        if math.hypot(x - 60, y - 68) < 12:
            continue
        r = 2 if rng.random() < 0.6 else 1
        circle(d, x, y, r, fill=BLACK)
        placed += 1
    circle(d, 60, 68, 8, outline=BLACK, width=1)
    circle(d, 44, 42, 11, fill=WHITE)
    circle(d, 44, 42, 11, outline=BLACK, width=2)
    circle(d, 44, 42, 5, fill=BLACK)
    circle(d, 42, 40, 2, fill=WHITE)
    pts = [(44 + 8 * math.cos(math.radians(t)), 60 + 8 * math.sin(math.radians(t)))
           for t in range(25, 156, 5)]
    d.line(pts, fill=BLACK, width=2, joint="curve")


def paint_gear(d, mid):
    if mid == 0:
        for x, y, w, h in SPOTS[:2]:
            rect(d, x, y, w, h)
    elif mid == 1:
        d.polygon([(27, 30), (39, 30), (33, 12)], fill=BLACK)
        d.polygon([(57, 30), (69, 30), (63, 12)], fill=BLACK)
        rect(d, 6, 66, 84, 4)
    elif mid == 2:
        rect(d, 45, 0, 6, 11)
        rect(d, 42, 0, 12, 5)
        rect(d, 10, 52, 5, 5)
        rect(d, 81, 52, 5, 5)
    elif mid == 3:
        for x0, y0, x1, y1 in TG:
            d.line([x0, y0, x1, y1], fill=BLACK, width=1)
    elif mid == 4:
        for x, y, w, h in STRIPES:
            rect(d, x, y, w, h)
    elif mid == 5:
        circle(d, 48, 52, 36, outline=BLACK, width=1)
        rect(d, 82, 16, 5, 5)
    elif mid == 6:
        d.polygon([(16, 50), (16, 74), (2, 62)], fill=WHITE, outline=BLACK)
        d.polygon([(80, 50), (80, 74), (94, 62)], fill=WHITE, outline=BLACK)
    elif mid == 7:
        for pts in ([(30, 26), (40, 26), (35, 8)], [(43, 24), (53, 24), (48, 6)],
                    [(56, 26), (66, 26), (61, 8)]):
            d.polygon(pts, fill=WHITE, outline=BLACK)
    elif mid == 8:
        for r in (3, 6, 9):
            circle(d, 48, 76, r, outline=BLACK, width=1)
    elif mid == 9:
        pass
    elif mid == 10:
        for x0, y0, x1, y1 in WHISK:
            d.line([x0, y0, x1, y1], fill=BLACK, width=1)
    elif mid == 11:
        for cx, cy in STARS[:2]:
            d.rectangle([cx - 4, cy - 1, cx + 4, cy + 1], fill=BLACK)
            d.rectangle([cx - 1, cy - 4, cx + 1, cy + 4], fill=BLACK)


def write_header(name, img1, output_path, src_label):
    raw = to_bitmap(img1)
    print(ascii_preview(img1))
    with open(output_path, "w") as f:
        f.write(f"#pragma once\n// auto-generated by tools/gen_morphs.py from {src_label}\n")
        f.write("// 96x96 XBM. 黒=描画。(RLEは未使用のため出力しない)\n\n")
        f.write(f"#define {name.upper()}_W 96\n#define {name.upper()}_H 96\n\n")
        f.write(f"static const unsigned char {name}_xbm[{len(raw)}] PROGMEM = {{\n")
        for i in range(0, len(raw), 12):
            f.write("  " + ", ".join(f"0x{b:02x}" for b in raw[i:i + 12]) + ",\n")
        f.write("};\n")
    img1.resize((288, 288), Image.NEAREST).convert("RGB").save(
        os.path.splitext(output_path)[0] + "_preview.png")
    print(f"wrote {output_path} raw={len(raw)}B")


def main():
    import argparse
    ap = argparse.ArgumentParser(description="FROZEN: 12形態idle手続き生成 (既定で書込禁止)")
    ap.add_argument("--force", action="store_true",
                    help="現行資産への上書きを許可する (通常は不要)")
    if not ap.parse_args().force:
        print("凍結中のため何も書き込みません (現行マスタ保護)。"
              "実行には --force が必須です。")
        raise SystemExit(2)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(root, "assets")
    disp = os.path.join(root, "src", "display", "art")
    contact = Image.new("RGB", (192 * 4, 192 * 3), (200, 200, 200))
    for mid in range(12):
        img = Image.new("L", (S, S), WHITE)
        d = ImageDraw.Draw(img)
        paint_base(d)
        paint_gear(d, mid)
        paint_face(d, 1000 + mid)
        img = img.point(lambda v: 0 if v < 128 else 255).convert("1", dither=Image.NONE)
        name = f"ink_m{mid:02d}_idle"
        img.convert("RGB").save(os.path.join(assets, name + ".png"))
        write_header(name, img, os.path.join(disp, f"art_{name}.h"), f"assets/{name}.png")
        contact.paste(img.convert("RGB").resize((192, 192), Image.NEAREST),
                      ((mid % 4) * 192, (mid // 4) * 192))
    contact.save(os.path.join(assets, "contact_morphs.png"))
    print("done 12 morphs + contact sheet")


if __name__ == "__main__":
    main()
