#!/usr/bin/env node
// tools/make_artjs.cjs — firmware XBM headers -> pc-companion/inkart.js
// Usage: node tools/make_artjs.cjs   (run from InkLife/ root)
// Reads: src/display/art_*.h (morph action art + greet),
//        src/display/pending_morphs/art_*.h (idle previews),
//        src/display/art_parts.h (fuse part bitmaps + PART_ROWS anchors).
// Writes: pc-companion/inkart.js  (window.InkArt, no deps)
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const DISP = path.join(ROOT, 'src', 'display');
const OUT = path.join(ROOT, 'pc-companion', 'inkart.js');

function read(f) { return fs.readFileSync(f, 'utf8'); }

function parseXbm(src) {
  // static const unsigned char NAME_xbm[1152] PROGMEM = { 0x.., ... };
  const m = src.match(/static const unsigned char (\w+)_xbm\[(\d+)\][\s\S]*?PROGMEM\s*=\s*\{([\s\S]*?)\};/);
  if (!m) return null;
  const bytes = [...m[3].matchAll(/0x([0-9a-fA-F]{2})/g)].map(x => parseInt(x[1], 16));
  return { name: m[1], size: +m[2], bytes };
}

const frames = {};
function addDir(dir) {
  for (const f of fs.readdirSync(dir)) {
    if (!/^art_.*\.h$/.test(f) || f === 'art_parts.h') continue;
    const r = parseXbm(read(path.join(dir, f)));
    if (!r) { console.error('skip (no xbm): ' + f); continue; }
    if (r.bytes.length !== r.size) { console.error('size mismatch: ' + f); process.exit(1); }
    frames[r.name] = Buffer.from(r.bytes).toString('hex');
  }
}
addDir(DISP);
// Base frames are legacy fallbacks (species-specific art_ink_m*.h are used).
for (const k of ['ink_idle', 'ink_happy', 'ink_eat', 'ink_sleep', 'ink_sad']) delete frames[k];

// ---- art_parts.h ----
const partsSrc = read(path.join(DISP, 'art_parts.h'));
const dims = {};
for (const m of partsSrc.matchAll(/(?:#define|static const uint8_t)\s+(PART_\w+_[WH])\b[^0-9]*(\d+)/g)) dims[m[1]] = +m[2];

function partBytes(sym) {
  const re = new RegExp('static const uint8_t ' + sym + '\\[\\] PROGMEM = \\{([\\s\\S]*?)\\};');
  const m = partsSrc.match(re);
  if (!m) { console.error('part not found: ' + sym); process.exit(1); }
  const bytes = [...m[1].matchAll(/0x([0-9a-fA-F]{2})/g)].map(x => parseInt(x[1], 16));
  return Buffer.from(bytes).toString('hex');
}
const anchors = {};
for (const m of partsSrc.matchAll(/static constexpr Anchor (ANCH_\w+)\[\] = \{([\s\S]*?)\};/g)) {
  const list = [...m[2].matchAll(/\{\s*(\d+),\s*(-?\d+),\s*(-?\d+)\s*\}/g)]
    .map(e => [+e[1], +e[2], +e[3]]);
  anchors[m[1]] = list;
}
const rows = [];
const rowsBlock = partsSrc.match(/static constexpr PartRow PART_ROWS\[\] = \{([\s\S]*?)\n\};/);
if (!rowsBlock) { console.error('PART_ROWS not found'); process.exit(1); }
const rowRe = /\{\s*(\d+),\s*(part_\w+_bmp),\s*(?:part_\w+_mask|nullptr),\s*(PART_\w+_W),\s*(PART_\w+_H),\s*(ANCH_\w+),\s*(\d+)\s*\}/g;
for (const m of rowsBlock[1].matchAll(rowRe)) {
  const [, gear, bmp, wSym, hSym, anch, cnt] = m;
  if (!anchors[anch] || anchors[anch].length !== +cnt) { console.error('anchor mismatch: ' + anch); process.exit(1); }
  rows.push({ gear: +gear, w: dims[wSym], h: dims[hSym], bmp: partBytes(bmp), anchors: anchors[anch] });
}

const out = '// inkart.js — AUTO-GENERATED by tools/make_artjs.cjs. Do not edit.\n' +
  '// XBM bit order: LSB-first row-major, black=1 (same as jpg2ink.py to_bitmap).\n' +
  '(function () {\n' +
  'var InkArt = ' + JSON.stringify({ frames, parts: rows }) + ';\n' +
  "if (typeof module !== 'undefined' && module.exports) module.exports = InkArt;\n" +
  "else if (typeof window !== 'undefined') window.InkArt = InkArt;\n" +
  '})();\n';
fs.writeFileSync(OUT, out);
console.log('frames=' + Object.keys(frames).length + ' parts(rows)=' + rows.length +
  ' bytes=' + fs.statSync(OUT).size);
